camel:
  springboot:
     main-run-controller: true
     name: splitter-service

app:
  input-dir: D:\\Workspace\\data\\input\\split\\
  output-dir: D:\\Workspace\\data\\output\\processed\\
  seda:
    queue-size: 200000
    concurrent-consumers: 16
  
  thread-pool:
    core-size: 25
    max-size: 100
    queue-size: 50000

  monitoring:
    log-interval-seconds: 30