camel:
  springboot:
     main-run-controller: true
     name: splitter-service

app:
  input-dir: D:\\Workspace\\data\\input\\split\\
  output-dir: D:\\Workspace\\data\\output\\processed\\
  seda:
    queue-size: 500000
    concurrent-consumers: 15
 